In [4]:
# Paramètres
import io
import pandas as pd
import boto3

# Connexion S3
s3_client = boto3.client(
 "s3",
 endpoint_url="http://minio.mon-namespace.svc.cluster.local:80", # service interne K8s
 aws_access_key_id="wer1Or8j7hXa3QGk2M3M",
 aws_secret_access_key="YtbyBd3Y0bEYeDy8aeX3lAf4JIUlKYlxY8lNVTVt",
 verify=False # à désactiver si SSL auto-signé ; sinon mettre True avec certificat valide
)

# Paramètres
bucket_name = "admindataanstat"
object_key = "Solde/FUSION/fusion_2015_2016.parquet"

# Télécharger l'objet depuis S3
obj = s3_client.get_object(Bucket=bucket_name, Key=object_key)

# Charger dans un DataFrame depuis le fichier Parquet
panel_solde_df = pd.read_parquet(io.BytesIO(obj['Body'].read()))

# Afficher un aperçu
panel_solde_df.head()

,124,125,126,171,190,195,200,201,202,203,...,530,531,532,533,780,BRUT MONTANT,MATRICULE||CODE_ORGANISME,MONTANT BRUT,Total général,source_fichier
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,34560,011242X15,None,None,012015.xlsx
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,42400,012856Q15,None,None,012015.xlsx
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,45600,013454N15,None,None,012015.xlsx
3,None,None,None,None,None,None,None,None,None,62380,...,None,None,None,None,None,800000,027861L25,None,None,012015.xlsx
4,513605,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,842646,047690HBQ,None,None,012015.xlsx

In [5]:
print (panel_solde_df.columns)

Index(['124', '125', '126', '171', '190', '195', '200', '201', '202', '203',
       ...
       '530', '531', '532', '533', '780', 'BRUT MONTANT',
       'MATRICULE||CODE_ORGANISME', 'MONTANT BRUT', 'Total général',
       'source_fichier'],
      dtype='object', length=168)

In [3]:
print(f"Nombre de lignes : {len(panel_solde_df)}")

Nombre de lignes : 369382

In [2]:
tab_source_fichier = panel_solde_df["source_fichier"].value_counts(dropna=False).sort_index()
tab_source_fichier_pct = panel_solde_df["source_fichier"].value_counts(normalize=True, dropna=False).sort_index()

pd.DataFrame({
    "Effectif": tab_source_fichier ,
    "Pourcentage (%)": (tab_source_fichier_pct * 100).round(2)
})

                Effectif  Pourcentage (%)
source_fichier
012015.xlsx       184576            49.97
022015.xlsx       184804            50.03

In [ ]:
nb_2016 = panel_solde_df[panel_solde_df['ANNEE_COLLECTE'] == 2016].shape[0]
print(f"Nombre d'observations en 2016 : {nb_2016}")

In [ ]:
# 2) GRADE contient "Non Fonctionnaire"
is_nf = df["GRADE"].astype(str).str.contains(r"\bnon\s*fonctionnaire\b", flags=re.I, na=False)

In [ ]:
df["TEST"] = (df["EMPLOI"].str.strip() == "") & df["GRADE"].str.contains(r"\bnon\s*fonctionnaire\b", flags=re.I, na=False)