In [6]:
# Paramètres
import io
import pandas as pd
import boto3

# Connexion S3
s3_client = boto3.client(
 "s3",
 endpoint_url="http://minio.mon-namespace.svc.cluster.local:80", # service interne K8s
 aws_access_key_id="wer1Or8j7hXa3QGk2M3M",
 aws_secret_access_key="YtbyBd3Y0bEYeDy8aeX3lAf4JIUlKYlxY8lNVTVt",
 verify=False # à désactiver si SSL auto-signé ; sinon mettre True avec certificat valide
)

# Paramètres
bucket_name = "admindataanstat"
object_key = "Solde/FUSION/fusion_2015_2020_feuille2.parquet"

# Télécharger l'objet depuis S3
obj = s3_client.get_object(Bucket=bucket_name, Key=object_key)

# Charger dans un DataFrame depuis le fichier Parquet
panel_solde_df = pd.read_parquet(io.BytesIO(obj['Body'].read()))

# Afficher un aperçu
panel_solde_df.head()

,124,125,126,171,190,195,200,201,202,203,...,541,542,819,997,MATRICULE II CODE_ORGANISME,241,265,288,298,587
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,62380,...,None,None,None,None,None,None,None,None,None,None
4,513605,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [8]:
list(panel_solde_df.columns)

['124',
 '125',
 '126',
 '171',
 '190',
 '195',
 '200',
 '201',
 '202',
 '203',
 '204',
 '207',
 '208',
 '209',
 '210',
 '211',
 '213',
 '214',
 '216',
 '217',
 '218',
 '221',
 '222',
 '223',
 '225',
 '226',
 '228',
 '229',
 '230',
 '231',
 '232',
 '234',
 '235',
 '236',
 '237',
 '238',
 '239',
 '240',
 '242',
 '243',
 '249',
 '251',
 '253',
 '257',
 '258',
 '259',
 '261',
 '262',
 '263',
 '264',
 '268',
 '269',
 '271',
 '272',
 '274',
 '275',
 '276',
 '278',
 '280',
 '281',
 '286',
 '287',
 '293',
 '294',
 '295',
 '296',
 '297',
 '299',
 '300',
 '310',
 '311',
 '312',
 '313',
 '320',
 '321',
 '322',
 '323',
 '330',
 '335',
 '336',
 '351',
 '352',
 '353',
 '368',
 '369',
 '380',
 '381',
 '382',
 '401',
 '402',
 '403',
 '404',
 '406',
 '410',
 '411',
 '412',
 '415',
 '416',
 '417',
 '418',
 '419',
 '420',
 '421',
 '422',
 '423',
 '424',
 '425',
 '426',
 '428',
 '429',
 '430',
 '433',
 '434',
 '435',
 '436',
 '437',
 '438',
 '440',
 '441',
 '442',
 '443',
 '444',
 '445',
 '447',
 '448',
 '449',
 '450',
 '451',
 '452',
 '453',
 '454',
 '455',
 '456',
 '457',
 '458',
 '461',
 '462',
 '463',
 '464',
 '465',
 '466',
 '467',
 '473',
 '474',
 '475',
 '486',
 '487',
 '488',
 '489',
 '491',
 '492',
 '494',
 '495',
 '496',
 '497',
 '498',
 '510',
 '520',
 '530',
 '531',
 '532',
 '533',
 '780',
 'BRUT MONTANT',
 'MATRICULE||CODE_ORGANISME',
 'MONTANT BRUT',
 'TOTAL GÉNÉRAL',
 'SOURCE_FICHIER',
 '129',
 '135',
 '390',
 '394',
 '468',
 '469',
 '470',
 '471',
 '485',
 '490',
 '493',
 '511',
 '512',
 '513',
 '540',
 '541',
 '542',
 '819',
 '997',
 'MATRICULE II CODE_ORGANISME',
 '241',
 '265',
 '288',
 '298',
 '587']

In [9]:
print(f"Nombre de lignes : {len(panel_solde_df)}")

Nombre de lignes : 15081957

In [11]:
tab_source_fichier = panel_solde_df["SOURCE_FICHIER"].value_counts(dropna=False).sort_index()
tab_source_fichier_pct = panel_solde_df["SOURCE_FICHIER"].value_counts(normalize=True, dropna=False).sort_index()

pd.DataFrame({
    "Effectif": tab_source_fichier ,
    "Pourcentage (%)": (tab_source_fichier_pct * 100).round(2)
})

                Effectif  Pourcentage (%)
SOURCE_FICHIER
012015.xlsx       184576             1.22
012016.xlsx       197988             1.31
012017.xlsx       202570             1.34
012018.xlsx       211829             1.40
012019.xlsx       216879             1.44
...                  ...              ...
122016.xlsx       202807             1.34
122017.xlsx       210644             1.40
122018.xlsx       217995             1.45
122019.xlsx       226263             1.50
122020.xlsx       243988             1.62

[72 rows x 2 columns]

In [12]:
# Forcer l'affichage complet
pd.set_option("display.max_rows", None)

# Construire et afficher le tableau
resultat = pd.DataFrame({
    "Effectif": tab_source_fichier,
    "Pourcentage (%)": (tab_source_fichier_pct * 100).round(2)
})

print(resultat)  # ou juste resultat si tu es dans un notebook

                Effectif  Pourcentage (%)
SOURCE_FICHIER
012015.xlsx       184576             1.22
012016.xlsx       197988             1.31
012017.xlsx       202570             1.34
012018.xlsx       211829             1.40
012019.xlsx       216879             1.44
012020.xlsx       228717             1.52
022015.xlsx       184804             1.23
022016.xlsx       197730             1.31
022017.xlsx       202377             1.34
022018.xlsx       214206             1.42
022019.xlsx       221017             1.47
022020.xlsx       231458             1.53
032015.xlsx       185378             1.23
032016.xlsx       197487             1.31
032017.xlsx       203355             1.35
032018.xlsx       214673             1.42
032019.xlsx       223098             1.48
032020.xlsx       232829             1.54
042015.xlsx       186892             1.24
042016.xlsx       198775             1.32
042017.xlsx       203901             1.35
042018.xlsx       217432             1.44
042019.xlsx       222799             1.48
042020.xlsx       233185             1.55
052015.xlsx       188493             1.25
052016.xlsx       199019             1.32
052017.xlsx       204981             1.36
052018.xlsx       217154             1.44
052019.xlsx       222784             1.48
052020.xlsx       233119             1.55
062015.xlsx       189610             1.26
062016.xlsx       199135             1.32
062017.xlsx       205708             1.36
062018.xlsx       218257             1.45
062019.xlsx       226185             1.50
062020.xlsx       235401             1.56
072015.xlsx       190489             1.26
072016.xlsx       199995             1.33
072017.xlsx       206994             1.37
072018.xlsx       218675             1.45
072019.xlsx       225695             1.50
072020.xlsx       237876             1.58
082015.xlsx       191620             1.27
082016.xlsx           96             0.00
082017.xlsx       209191             1.39
082018.xlsx       219873             1.46
082019.xlsx       226284             1.50
082020.xlsx       236784             1.57
092015.xlsx       192026             1.27
092016.xlsx       200367             1.33
092017.xlsx       208233             1.38
092018.xlsx       219022             1.45
092019.xlsx       224353             1.49
092020.xlsx       241494             1.60
102015.xlsx       193956             1.29
102016.xlsx       200892             1.33
102017.xlsx       208150             1.38
102018.xlsx       218062             1.45
102019.xlsx       223970             1.49
102020.xlsx       242857             1.61
112015.xlsx       194883             1.29
112016.xlsx       201920             1.34
112017.xlsx       209502             1.39
112018.xlsx       217222             1.44
112019.xlsx       225114             1.49
112020.xlsx       244768             1.62
122015.xlsx       196096             1.30
122016.xlsx       202807             1.34
122017.xlsx       210644             1.40
122018.xlsx       217995             1.45
122019.xlsx       226263             1.50
122020.xlsx       243988             1.62